//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#import <XCTest/XCTest.h>
#import "___VARIABLE_sceneName___Worker.h"

@interface ___VARIABLE_sceneName___WorkerTests : XCTestCase

@property (strong, nonatomic) ___VARIABLE_sceneName___Worker* sut;

@end

@implementation ___VARIABLE_sceneName___WorkerTests

- (void)setUp
{
  [super setUp];
  [self setup___VARIABLE_sceneName___Worker];
}

- (void)tearDown
{
  [super tearDown];
}

#pragma mark Test setup

- (void)setup___VARIABLE_sceneName___Worker
{
  self.sut = [[___VARIABLE_sceneName___Worker alloc] init];
}

#pragma mark Tests

- (void)testExample
{
  // Given
  
  // When
  
  // Then
}

@end
