//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#import "___VARIABLE_sceneName___Common.h"

@class ___VARIABLE_sceneName___ViewController;
@protocol ___VARIABLE_sceneName___DataStore;

@protocol ___VARIABLE_sceneName___RoutingLogic
//- (void)routeToSomewhere:(UIStoryboardSegue *)segue;
@end

@protocol ___VARIABLE_sceneName___DataPassing
@property (strong, nonatomic) id<___VARIABLE_sceneName___DataStore> dataStore;
@end

@interface ___VARIABLE_sceneName___Router: NSObject <___VARIABLE_sceneName___RoutingLogic, ___VARIABLE_sceneName___DataPassing>
@property (weak, nonatomic) ___VARIABLE_sceneName___ViewController *viewController;
@property (strong, nonatomic) id<___VARIABLE_sceneName___DataStore> dataStore;
@end
