//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#import "___VARIABLE_sceneName___Common.h"

@protocol ___VARIABLE_sceneName___PresentationLogic;

@protocol ___VARIABLE_sceneName___BusinessLogic
- (void)doSomething:(___VARIABLE_sceneName___DoSomethingRequest *)request;
@end

@protocol ___VARIABLE_sceneName___DataStore
//@property (strong, nonatomic) NSString *name;
@end

@interface ___VARIABLE_sceneName___Interactor: NSObject <___VARIABLE_sceneName___BusinessLogic, ___VARIABLE_sceneName___DataStore>
@property (strong, nonatomic) id<___VARIABLE_sceneName___PresentationLogic> presenter;
@end
