//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#import "___VARIABLE_sceneName___Common.h"

@protocol ___VARIABLE_sceneName___BusinessLogic;
@protocol ___VARIABLE_sceneName___RoutingLogic;
@protocol ___VARIABLE_sceneName___DataPassing;

@protocol ___VARIABLE_sceneName___DisplayLogic
- (void)displaySomething:(___VARIABLE_sceneName___DoSomethingViewModel *)viewModel;
@end

@interface ___VARIABLE_sceneName___ViewController: UIViewController <___VARIABLE_sceneName___DisplayLogic>
@property (strong, nonatomic) id<___VARIABLE_sceneName___BusinessLogic> interactor;
@property (strong, nonatomic) NSObject<___VARIABLE_sceneName___RoutingLogic, ___VARIABLE_sceneName___DataPassing> *router;
@end
