//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#import "___VARIABLE_sceneName___Router.h"
//#import "SomewhereViewController.h"

@interface ___VARIABLE_sceneName___Router ()
@end

@implementation ___VARIABLE_sceneName___Router

#pragma mark Routing

//- (void)routeToSomewhere:(UIStoryboardSegue *)segue
//{
//  if (segue != nil) {
//    SomewhereViewController *destinationVC = (SomewhereViewController *)segue.destinationViewController;
//    id<SomewhereDataStore> destinationDS = destinationVC.router.dataStore;
//    [self passDataToSomewhere:self.dataStore destination:destinationDS];
//  } else {
//    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
//    SomewhereViewController *destinationVC = [storyboard instantiateViewControllerWithIdentifier:@"SomewhereViewController"];
//    id<SomewhereDataStore> destinationDS = destinationVC.router.dataStore;
//    [self passDataToSomewhere:self.dataStore destination:destinationDS];
//    [self navigateToSomewhere:self.viewController destination:destinationVC];
//  }
//}

#pragma mark Navigation

//- (void)navigateToSomewhere:(___VARIABLE_sceneName___ViewController *)source destination:(SomewhereViewController *)destination
//{
//  [source showViewController:destination sender:nil];
//}

#pragma mark Passing data

//- (void)passDataToSomewhere:(id<___VARIABLE_sceneName___DataStore>)source destination:(id<SomewhereDataStore>)destination
//{
//  destination.name = source.name;
//}

@end
