//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#ifndef ___PROJECTNAMEASIDENTIFIER_______VARIABLE_sceneName____Common_h
#define ___PROJECTNAMEASIDENTIFIER_______VARIABLE_sceneName____Common_h

#import <UIKit/UIKit.h>
#import "___VARIABLE_sceneName___Models.h"
#import "___VARIABLE_sceneName___ViewController.h"
#import "___VARIABLE_sceneName___Interactor.h"
#import "___VARIABLE_sceneName___Presenter.h"
#import "___VARIABLE_sceneName___Router.h"

#endif
