//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#pragma mark Use cases

#import "___VARIABLE_sceneName___Models.h"

@implementation ___VARIABLE_sceneName___DoSomethingRequest
@end

@implementation ___VARIABLE_sceneName___DoSomethingResponse
@end

@implementation ___VARIABLE_sceneName___DoSomethingViewModel
@end
