//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

#import <UIKit/UIKit.h>

#pragma mark Use cases

@interface ___VARIABLE_sceneName___DoSomethingRequest: NSObject
@end

@interface ___VARIABLE_sceneName___DoSomethingResponse: NSObject
@end

@interface ___VARIABLE_sceneName___DoSomethingViewModel: NSObject
@end
